variable "instance_count" {}
variable "instance_type" {}
variable "public_sg" {}
variable "public_subnets" {}
variable "volume_size" {}
variable "lb_target_group_arn" {}
#variable "key_name" {}
#variable "public_key_path" {}
#variable "user_data_path" {}
